version: 2
jobs:
  build:
    machine: true
    steps:
       - checkout

       - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose

       - run:
          name: Build -- Init Database
          command: docker-compose run --rm odoo odoo --stop-after-init -i main

       - run:
          name: Setup Log Folder For Reports
          command: mkdir -p ./log && sudo chmod 777 ./log

       - run:
          name: Run Test
          command: docker-compose run --rm odoo run_test.sh

       - run:
          name: Codacy Coverage
          command: /usr/local/bin/python-codacy-coverage -r ./log/coverage.xml

       - store_test_results:
          path: ./log




