version: 2
jobs:
  build:
    docker:
      - image: centos:7

    steps:
       - checkout

       - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose

       - run:
          name: Run Tests
          command: docker-compose run --rm odoo run_test.sh
